version: "3"
services:
  mailplug-redis:
    container_name: mailplug-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: alexgim961101/mailplug-redis
    ports:
      - "6379:6379"
  mailplug-database:
    container_name: mailplug-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: alexgim961101/mailplug-database
    environment:
      - MARIADB_DATABASE=mailplug
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  mailplug-app:
    container_name: mailplug-app
    build: .
    depends_on:
      - mailplug-database
      - mailplug-redis
    image: alexgim961101/mailplug-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    restart: always
