spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mailplug
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  cache:
    type: redis
    redis:
      cache-null-values: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mailplug-database:3306/mailplug
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        storage-engine: innodb
    hibernate:
      ddl-auto: create
    show-sql: true
    format_sql: true
  cache:
    type: redis
    redis:
      host: mailplug-redis
      port: 6379
  sql:
    init:
      mode: never

