name: Java CI/CD with Gradle and Docker

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with gradlew
        run: ./gradlew clean build -x test --stacktrace

      # 도커 로그인
      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: alexgim961101
          password: dckr_pat_TTJ-o-UZExLLuSq43rZXAcejiz0

      - name: Docker Hub build And push
        run: |
          docker build -t alexgim961101/mailplug-app .
          docker images
          docker push alexgim961101/mailplug-app

      - name: Deploy to Prod EC2 Server
        uses: appleboy/ssh-action@master
        with:
          host: 43.202.142.100
          username: ec2-user
          key: ${SSH_KEY}
          port: 22
          # docker-compose가 있는 디렉토리로 이동해야 수행됩니다.
          script: |
            cd /home/ubuntu/mailplug-test/
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP }}
            sudo docker-compose up -d
            sudo docker image prune -f

